### ISSUE TITLE
Document Datasets 

### ISSUE THREAD

**Issue by EliGurarie** [EliGurarie/smoove#4]
Kestrel (from Movebank) and Simulation simSweep (from vignette).

**Comment by faridcher** [comment]
I don't know what to write about `Kestrel`, `Lamprey` or `simSweep` . I stubbed a doc page in `dataset.r` for them though.

**Comment by EliGurarie** [comment]
- `Lamprey` are removed. 
- `Kestrel` is from the "(EBD) Lesser Kestrels" open access dataset on Movebank (perhaps get some key information, esp. references from there)
- `simSweep` is generated in the vignette, which should provide the basis for the description, including (in particular) the code to generate it.

**Comment by faridcher** [comment]
#14
