### ISSUE TITLE
Make (or check if) other estimation functions are POSIX compatible.

### ISSUE THREAD

**Issue by EliGurarie** [EliGurarie/smoove#7]
They might be ... but its worth checking, and maybe adding a "time.unit" parameter.

**Comment by faridcher** [comment]
please clarify which functions require this feature? The only function that supports this is `estimateRACVM`.

**Comment by faridcher** [comment]
I added support for `estimateUCVM`. Other estimation functions like `estimateCVM.crw` etc are called by `estimateUCVM` and they are not intended to be called directly.

**Comment by faridcher** [comment]
#16
